spring.application.name=SSOJ

spring.datasource.url=jdbc:postgresql://localhost:5432/ssoj
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.data.redis.host=localhost
spring.data.redis.port=6379

worker.poll-delay-ms=1000
worker.executor.java.image=eclipse-temurin:17-jdk
worker.executor.python.image=python:3.11
