spring.application.name=SSOJ

spring.datasource.url=jdbc:postgresql://localhost:5432/ssoj
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.data.redis.host=localhost
spring.data.redis.port=6379

worker.poll-delay-ms=1000
